# Generated by Django 5.1.1 on 2024-09-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
