# Generated by Django 5.1.1 on 2024-09-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='created_at',
            new_name='purchased_at',
        ),
    ]
